### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alloynetworks** [antIggl/xrpl-unl-manager#1]
Excellent work! Could you please tell me under what License this is published?

**Comment by antIggl** [comment]
Thank you for your message.
The university legal advisor works on a formal document, in order to avoid any possible contracts violations. But we have a very first indication for it.
Since this work is funded by UBRI and the Institute For the Future in the University of Nicosia, there will be a kind of open-source software license, very similar to the one ```rippled``` is licenced with. Additional to this, we would require acknowledgements to this work.

I will come back when I have an update.

**Comment by nbougalis** [comment]
Oh that's just awesome! Hi Antonis!

**Comment by alloynetworks** [comment]
@antIggl - Here's a snippet that I wrote to fetch manifests. Using the `utils.py`
```py
import utils
import sqlite3
import codecs
conn = sqlite3.connect('wallet.db')
c = conn.cursor()
for row in c.execute('select quote(RawData) from ValidatorManifests'):
     b64 = codecs.encode(codecs.decode(row[0][2:-1], 'hex'), 'base64').decode()
     print(utils.decodeManifest(b64))
conn.close()
```
Works fine! Just a thing to note, that manifests that have domains in them aren't decoded correctly, from my initial observation.

**Comment by klitoschr** [comment]
Hello everyone, this is ongoing work with more to come. We will be inviting people to contribute to this work so please feel free to provide feedback or recommendations for future implementation. 

We acknowledge that this work is funded by the Ripple’s Impact Fund, an advised fund of Silicon Valley Community Foundation (Grant id: 2018–188546).

**Comment by klitoschr** [comment]
> @antIggl - Here's a snippet that I wrote to fetch manifests. Using the `utils.py`
> 
> ```python
> import utils
> import sqlite3
> import codecs
> conn = sqlite3.connect('wallet.db')
> c = conn.cursor()
> for row in c.execute('select quote(RawData) from ValidatorManifests'):
>      b64 = codecs.encode(codecs.decode(row[0][2:-1], 'hex'), 'base64').decode()
>      print(utils.decodeManifest(b64))
> conn.close()
> ```
> 
> Works fine! Just a thing to note, that manifests that have domains in them aren't decoded correctly, from my initial observation.

excellent!

**Comment by klitoschr** [comment]
> Oh that's just awesome! Hi Antonis!

Hi Nik :)

**Comment by klitoschr** [comment]
> Excellent work! Could you please tell me under what License this is published?

Complementary to the technical work we are publishing a Series of Medium articles for exposing the work. Check them out here: [https://t.co/oakgJ7yBbG?amp=1](https://t.co/oakgJ7yBbG?amp=1)

**Comment by alloynetworks** [comment]
Thanks for that. Would it be possible to rename the repository to accurately reflect what it is - `xrpl-unl-manager` ?

**Comment by antIggl** [comment]
> @antIggl - Here's a snippet that I wrote to fetch manifests. Using the `utils.py`
> 
> ```python
> import utils
> import sqlite3
> import codecs
> conn = sqlite3.connect('wallet.db')
> c = conn.cursor()
> for row in c.execute('select quote(RawData) from ValidatorManifests'):
>      b64 = codecs.encode(codecs.decode(row[0][2:-1], 'hex'), 'base64').decode()
>      print(utils.decodeManifest(b64))
> conn.close()
> ```
> 
> Works fine! Just a thing to note, that manifests that have domains in them aren't decoded correctly, from my initial observation.

Thank you for reporting this. Thank you for the snippet too.
I will have a look at it in a few days.

**Comment by antIggl** [comment]
> Thanks for that. Would it be possible to rename the repository to accurately reflect what it is - `xrpl-unl-manager` ?

You are right. Done!

**Comment by antIggl** [comment]
> Oh that's just awesome! Hi Antonis!

Hi Nik!
Thanks.

**Comment by antIggl** [comment]
License file was added.
bf7393fa3af16f2711c4f391edcee684398a57df

I'm closing the issue.
